name: Demo Push

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file Dockerfile --tag goapp-foo
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          VERSION=${{ github.ref }}
          docker tag goapp-foo $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
